### ISSUE TITLE
Keyframe offset by one in the timeline

### ISSUE THREAD

**Issue by vspin** [Straafe/unity-editor-tools#2]
Everything works except that the reversed animation keyframes begin at 1 in the timeline, and not at zero.

Edit. Just noticed the following two lines: 

```
//K.time = clipLength - K.time - (1 / clip.frameRate); //Reversed sprite clips may be offset by 1 frame time
K.time = clipLength - K.time;
```

**Comment by Straafe** [comment]
Yea, I do not use sprites very often and am not smart enough to know why for sprites it is offset like that, but glad you spotted that line
